// Worker *secrets*, declared by hand.
//
// worker-configuration.d.ts is generated by `wrangler types` from
// wrangler.jsonc, and secrets are deliberately not in wrangler.jsonc — they are
// set with `wrangler secret put` (and, locally, in a gitignored `.dev.vars`).
// So the generated file cannot know about them, and regenerating it must not be
// able to drop them: they live here, merged into the same `Cloudflare.Env` the
// `env` from 'cloudflare:workers' resolves to.
//
// Anything added here is a deploy step. See docs/SAAS.md (Task 12) for the
// runbook, and .dev.vars.example for local development.
declare namespace Cloudflare {
  interface Env {
    /** HMAC key for login codes at rest (`server/codes.ts`). */
    CODE_HMAC_SECRET: string
    /**
     * The key channel tokens are signed with (`server/channel-token.ts`), and
     * the one value this Worker shares with another: the relay verifies tokens
     * offline with the same string. `wrangler secret put RELAY_SIGNING_SECRET`
     * on *both* Workers, with the same value, or nothing bridges. Rotating it
     * invalidates every outstanding channel token — blast radius, one TTL.
     */
    RELAY_SIGNING_SECRET: string
    /**
     * The relay to dial, e.g. `wss://relay.flue.sh`, handed to the caller
     * alongside every channel token.
     *
     * Read twice, in two schemes, and there is deliberately no second variable
     * for the other one: `server/devices.ts` swaps `wss:`→`https:` for the
     * document navigation that opens a session, and `server/refresh-token.ts`
     * makes the same swap to get the one browser **origin** allowed to call
     * `/api/relay-token` cross-origin. So this value is also the CORS
     * allowance: point it at a relay a deployment does not use and the refresh
     * is refused rather than half-working.
     *
     * Not a secret, and deliberately not in wrangler.jsonc either: that file's
     * bindings are typed by the *generated* worker-configuration.d.ts, and a
     * value declared in both places is one `pnpm cf-typegen` away from a
     * duplicate declaration. It travels with the secrets instead — one
     * `.dev.vars` locally, one deploy step in docs/SAAS.md.
     */
    RELAY_URL: string
  }
}
