// Worker *secrets*, declared by hand.
//
// worker-configuration.d.ts is generated by `wrangler types` from
// wrangler.jsonc, and secrets are deliberately not in wrangler.jsonc — they are
// set with `wrangler secret put` (and, locally, in a gitignored `.dev.vars`).
// So the generated file cannot know about them, and regenerating it must not be
// able to drop them: they live here, merged into the same `Cloudflare.Env` the
// `env` from 'cloudflare:workers' resolves to.
//
// Anything added here is a deploy step. See docs/SAAS.md (Task 12) for the
// runbook, and .dev.vars.example for local development.
declare namespace Cloudflare {
  interface Env {
    /** HMAC key for login codes at rest (`server/codes.ts`). */
    CODE_HMAC_SECRET: string
  }
}
