/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiRelayTokenRouteImport } from './routes/api.relay-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRelayTokenRoute = ApiRelayTokenRouteImport.update({
  id: '/api/relay-token',
  path: '/api/relay-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/relay-token': typeof ApiRelayTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/relay-token': typeof ApiRelayTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices': typeof DevicesRoute
  '/enroll': typeof EnrollRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/relay-token': typeof ApiRelayTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/devices' | '/enroll' | '/login' | '/terms' | '/api/relay-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devices' | '/enroll' | '/login' | '/terms' | '/api/relay-token'
  id:
    | '__root__'
    | '/'
    | '/devices'
    | '/enroll'
    | '/login'
    | '/terms'
    | '/api/relay-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesRoute: typeof DevicesRoute
  EnrollRoute: typeof EnrollRoute
  LoginRoute: typeof LoginRoute
  TermsRoute: typeof TermsRoute
  ApiRelayTokenRoute: typeof ApiRelayTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/relay-token': {
      id: '/api/relay-token'
      path: '/api/relay-token'
      fullPath: '/api/relay-token'
      preLoaderRoute: typeof ApiRelayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesRoute: DevicesRoute,
  EnrollRoute: EnrollRoute,
  LoginRoute: LoginRoute,
  TermsRoute: TermsRoute,
  ApiRelayTokenRoute: ApiRelayTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
